var defaultItemGrid = {};
var dungeonchestsInit = {};
var dungeonbeatenInit = {};
var prizesInit = {};
var medallionsInit = {};
var itemsMin = {};
var itemsMax = {};

var gameItems = {};
gameItems.zelda3 = [
  "bow",
  "boomerang",
  "hookshot",
  "hammer",
  "firerod",
  "glove",
  "moonpearl",
  "sword",
  "tunic",
  "shield",
  "bombos",
  "ether",
  "quake",
  "somaria",
  "lantern",
  "flute",
  "book",
  "boots",
  "flippers",
  "mirror",
  "shovel",
  "mushroom",
  "powder",
  "bottle",
  "cape",
  "icerod",
  "byrna",
  "net",
  "silvers",
  "woods",
  "mpupgrade",
  "bomb",
  "heartcontainer",
  "heartpiece",
  "agahnim",

  "boss0",
  "boss1",
  "boss2",
  "boss3",
  "boss4",
  "boss5",
  "boss6",
  "boss7",
  "boss8",
  "boss9",

  "medallion0",
  "medallion1",
  "medallion2",
  "medallion3",
  "dungeon0",
  "dungeon1",
  "dungeon2",
  "dungeon3"
];
gameItems.metroid3 = [
  "charge",
  "ice",
  "wave",
  "spazer",
  "plasma",
  "varia",
  "gravity",
  "morph",
  "bombs",
  "springball",
  "screw",
  "hijump",
  "space",
  "speed",
  "missile",
  "supermissile",
  "powerbomb",
  "grappling",
  "xray",
  "kraid",
  "phantoon",
  "draygon",
  "ridley",
  "etank",
  "rtank",

  "boss0",
  "boss1",
  "boss2",
  "boss3",
  "boss4",
  "boss5",
  "boss6",
  "boss7",
  "boss8",
  "boss9"
];

gameItems.averge1 = [
	"axiom-disruptor",
	"nova",
	"multi-disruptor",
	"kilver",
	"hypo-atomizer",
	"voranj",
	"shards",
	"quantum-variegator",
	"reflector",
	"ion-beam",
	"tethered-charge",
	"inertial-pulse",
	"data-bomb",
	"orbital-discharge",
	"lightning-gun",
	"flamethrower",
	"distortion-field",
	"turbine-pulse",
	"reverse-slicer",
	"firewall",
	"heat-seeker",
	"scissor-beam",
	"fat-beam",
	"laser-drill",
	"field-disruptor",
	"bioflux-accelerator-1",
	"modified-lab-coat",
	"enhanced-drone-launch",
	"trenchcoat",
	"drone-teleport",
	"sudran-key",
	"red-coat",
	"passcode-tool",
	"bioflux-accelerator-2",
	"remote-drone",
	"address-disruptor-1",
	"address-disruptor-2",
	"grapple",
	"address-bomb",
	"power-node-fragment",
	"power-node",
	"health-node-fragment",
	"health-node",
	"size-node",
	"range-node"
];

var itemsInit = {
  blank:          false,

  tunic:          1,
  sword:          0,
  shield:         0,
  bow:            false,
  boomerang:      0,
  bomb:           0,
  hookshot:       false,
  powder:         false,
  mushroom:       false,
  firerod:        false,
  icerod:         false,
  bombos:         false,
  ether:          false,
  quake:          false,
  lantern:        false,
  hammer:         false,
  flute:          0,
  shovel:         false,
  net:            false,
  book:           false,
  bottle:         0,
  somaria:        false,
  byrna:          false,
  cape:           false,
  mirror:         false,

  boots:          false,
  glove:          0,
  flippers:       false,
  moonpearl:      false,
  mpupgrade:      0,
  silvers:        false,
  woods:          false,

  heartcontainer: 0,
  heartpiece:     0,

  agahnim:        0,

  charge:         false,
  ice:            false,
  wave:           false,
  spazer:         false,
  plasma:         false,
  varia:          false,
  gravity:        false,
  morph:          false,
  bombs:          false,
  springball:     false,
  screw:          false,
  hijump:         false,
  space:          false,
  speed:          false,
  missile:        0,
  supermissile:   0,
  powerbomb:      0,
  grappling:      false,
  xray:           false,
  kraid:          false,
  phantoon:       false,
  draygon:        false,
  ridley:         false,
  etank:          0,
  rtank:          0,

	"axiom-disruptor": false,
	"nova": false,
	"multi-disruptor": false,
	"kilver": false,
	"hypo-atomizer": false,
	"voranj": false,
	"shards": false,
	"quantum-variegator": false,
	"reflector": false,
	"ion-beam": false,
	"tethered-charge": false,
	"inertial-pulse": false,
	"data-bomb": false,
	"orbital-discharge": false,
	"lightning-gun": false,
	"flamethrower": false,
	"distortion-field": false,
	"turbine-pulse": false,
	"reverse-slicer": false,
	"firewall": false,
	"heat-seeker": false,
	"scissor-beam": false,
	"fat-beam": false,
	"laser-drill": false,
	"field-disruptor": false,
	"bioflux-accelerator-1": false,
	"modified-lab-coat": false,
	"enhanced-drone-launch": false,
	"trenchcoat": false,
	"drone-teleport": false,
	"sudran-key": false,
	"red-coat": false,
	"passcode-tool": false,
	"bioflux-accelerator-2": false,
	"remote-drone": false,
	"address-disruptor-1": false,
	"address-disruptor-2": false,
	"grapple": false,
	"address-bomb": false,
	"power-node-fragment": 0,
	"power-node": 0,
	"health-node-fragment": 0,
	"health-node": 0,
	"size-node": 0,
	"range-node": 0
};
