var defaultItemGrid = {};
var dungeonchestsInit = {};
var dungeonbeatenInit = {};
var prizesInit = {};
var medallionsInit = {};
var itemsMin = {};
var itemsMax = {};

var gameItems = {};
gameItems.zelda3 = [
    "bow",
    "boomerang",
    "hookshot",
    "hammer",
    "firerod",
    "glove",
    "moonpearl",
    "sword",
    "tunic",
    "shield",
    "bombos",
    "ether",
    "quake",
    "somaria",
    "lantern",
    "flute",
    "book",
    "boots",
    "flippers",
    "mirror",
    "shovel",
    "mushroom",
    "powder",
    "bottle",
    "cape",
    "icerod",
    "byrna",
    "net",
    "silvers",
    "mpupgrade",
    "bomb",
    "heartcontainer",
    "heartpiece",
    "agahnim",

    "boss0",
    "boss1",
    "boss2",
    "boss3",
    "boss4",
    "boss5",
    "boss6",
    "boss7",
    "boss8",
    "boss9",

    "medallion0",
    "medallion1",
    "medallion2",
    "medallion3",
    "dungeon0",
    "dungeon1",
    "dungeon2",
    "dungeon3"
];
gameItems.metroid3 = [
    "charge",
    "ice",
    "wave",
    "spazer",
    "plasma",
    "varia",
    "gravity",
    "morph",
    "bombs",
    "springball",
    "screw",
    "hijump",
    "space",
    "speed",
    "missile",
    "supermissile",
    "powerbomb",
    "grappling",
    "xray",
    "kraid",
    "phantoon",
    "draygon",
    "ridley",
    "etank",
    "rtank",

    "boss0",
    "boss1",
    "boss2",
    "boss3",
    "boss4",
    "boss5",
    "boss6",
    "boss7",
    "boss8",
    "boss9"
];

var itemsInit = {
    blank: false,

    tunic: 1,
    sword: 0,
    shield: 0,
    bow: false,
    boomerang: 0,
    bomb: 0,
    hookshot: false,
    powder: false,
    mushroom: false,
    firerod: false,
    icerod: false,
    bombos: false,
    ether: false,
    quake: false,
    lantern: false,
    hammer: false,
    flute: false,
    shovel: false,
    net: false,
    book: false,
    bottle:0,
    somaria: false,
    byrna: false,
    cape: false,
    mirror: false,

    boots: false,
    glove: 0,
    flippers: false,
    moonpearl: false,
    mpupgrade: 0,
    silvers: false,

    heartcontainer: 0,
    heartpiece: 0,

    agahnim: 0,

    charge: false,
    ice: false,
    wave: false,
    spazer: false,
    plasma: false,
    varia: false,
    gravity: false,
    morph: false,
    bombs: false,
    springball: false,
    screw: false,
    hijump: false,
    space: false,
    speed: false,
    missile: 0,
    supermissile: 0,
    powerbomb: 0,
    grappling: false,
    xray: false,
    kraid: false,
    phantoon: false,
    draygon: false,
    ridley: false,
    etank:0,
    rtank:0
};
